---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:22.04
    pre_build_image: false
    # dockerfile: Dockerfile.j2
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
scenario:
  name: default
verifier:
  name: ansible

# dependency:
#   name: galaxy
# driver:
#   name: docker
# platforms:
#   - name: Ubuntu 22.04
#     image: hub.docker.com/_/ubuntu:20.04
#     privileged: true
# provisioner:
#   name: ansible
#   lint:
#     name: ansible-lint
# scenario:
#   name: default
