---
- name: Verify that our ansible version is 2.10 or higher
  ansible.builtin.assert:
    that: "{{ ansible_version.full is version('2.10', '>=') }}"

- block:
  - name: Update and upgrade apt packages
    apt:
      autoremove: true
      autoclean: true
      upgrade: 'yes' 
      update_cache: true
      cache_valid_time: 86400 # 1 day
        #    become: true
    async: 600
    poll: 0
    register: update_and_upgrade_async

  - name: Wait until apt-get update/upgrade is complete (delay=5)
    ansible.builtin.async_status:
      jid: '{{ update_and_upgrade_async.ansible_job_id }}'
    register: update_and_upgrade_async_result
    until: update_and_upgrade_async_result.finished
    retries: 120
    delay: 5

  - name: Output 
    debug:
      var: update_and_upgrade_async_result

  - name: Write the output of apt-get update/upgrade to /tmp/apt-get-output.log if changes ocurred
    copy:
      content: "{{ update_and_upgrade.stdout }}"
      dest: "/tmp/apt-get-output.log"
    when: update_and_upgrade_async_result.changed
  become: true
