---
- ansible.builtin.include_tasks: dependencies.yml
  tags:
    - dependencies
- block:
  become: true
  - ansible.builtin.include_tasks: apt-setup.yml
  - ansible.builtin.include_tasks: packages.yml
    tags:
      - packages
  - ansible.builtin.include_tasks: applications.yml
    tags:
      - applications
  - ansible.builtin.include_tasks: languages.yml
    tags:
      - languages 

        # - ansible.builtin.include_tasks: configure.yml
        #   tags:
        #     - configure
