---
- ansible.builtin.import_tasks: dependencies.yml
  tags:
    - dependencies

- block:
  - ansible.builtin.import_tasks: apt-setup.yml
  - ansible.builtin.import_tasks: packages.yml
    tags:
      - packages
  - ansible.builtin.import_tasks: applications.yml
    tags:
      - applications
  - ansible.builtin.import_tasks: languages.yml
    tags:
      - languages 
  become: true
