---
# documentation:
# https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
# https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
#
# TODO:
# - create variable for ssh_key_path
# - upgrade to ansible 2.12 for passphrase support
# - add option to backup existing key if one exists instead of always failing if key exists
# - add option to specify email-address, and username variable from vars

- name: Verify username
  ansible.builtin.pause:
    prompt: 'Generate SSH Key for user: "{{ ansible_user_id }}"? Press return to continue. Press Ctrl+c and then "a" to abort'
    echo: false
  tags:
    - always

- name: Generate SSH Key for GitHub
  tags:
    - generate
  vars:
    github_ssh_key_file: "{{ (ansible_env.HOME, '.ssh', 'id_git_rsa') | ansible.builtin.path_join }}"
  block:
    - name: Enter email address
      ansible.builtin.pause:
        prompt: Enter email address
      register: email_address

    - name: Create .ssh directory (mode 0700) if DNE
      ansible.builtin.file:
        path: "{{ (ansible_env.HOME, '.ssh') | ansible.builtin.path_join }}"
        state: directory
        mode: "0700"

    - name: Generate SSH key
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_file: "{{ github_ssh_key_file }}"

    - name: Evaluating the authentication agent & adding the key
      ansible.builtin.shell: |
        eval "$(ssh-agent)"
        ssh-add "{{ github_ssh_key_file }}"
      register: shell_cmd
      failed_when: shell_cmd.rc != 0
      changed_when: shell_cmd.rc != 0

- name: Upload SSH Key to GitHub
  tags:
    - upload
  block:
    - name: Enter GitHub Access Token
      ansible.builtin.pause:
        prompt: Enter Personal GitHub Access Token
        echo: false
      register: access_token
      no_log: true

    - name: Add SSH key to public GitHub account
      ansible.builtin.uri:
        url: https://api.github.com/user/keys
        method: POST
        headers:
          Accept: application/vnd.github+json
          Authorization: Bearer {{ access_token.user_input }}
          X-GitHub-Api-Version: 2022-11-28
        body_format: json
        body:
          key: "{{ lookup('ansible.builtin.file', github_ssh_key_file) }}"
          title: ssh_rsa {{ ansible_hostname }}-{{ ansible_date_time.date }}
        status_code: 201
      register: post_ssh_key

    - name: Print API output
      ansible.builtin.debug:
        msg: "{{ post_ssh_key }}"
