---
name: ansible-lint

on:
  pull_request:
    branches: ["master"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
        with:
          working_directory: "${{ github.workspace }}"

      # - name: Set up Python 3.
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'

      # - name: Install test dependencies.
      #   run: pip3 install ansible

      # - name: Install ansible collection
      #   run: ansible-galaxy install -r requirements.yml -p ./collections

      # - name: Install ansible-lint from source
      #   run: pip3 install git+https://github.com/ansible/ansible-lint

      # - name: Run ansible-lint
      #   run: ansible-lint
      
      # - name: Run ansible-lint
      #   uses: ansible/ansible-lint@main
      
      #   env:
      #     ANSIBLE_COLLECTIONS_PATH: ./collections
